apiVersion: v1alpha
kind: imagerunner

suites:
  - name: photon-js-webdriverio
    image: suncup/photon-js:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: ls -la demo-webdriverio
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: us-west-1
      SAUCE_BUILD_TYPE: Orchestrate
    artifacts:
      - "/root/.npm/_logs/*.log"