apiVersion: v1alpha
kind: imagerunner

suites:
  - name: photon-java
    image: suncup/photon-java:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: mvn -pl best-practice test -Dtest=DesktopTests
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate
      NASA_API_KEY: